### ISSUE TITLE
Corevis Failing

### ISSUE THREAD

**Issue by jgautier** [Voxer/node-corevis#3]
```
jgautier@sjc1-julian-01:~ $ sudo corevis core.44066 > blah.html
> loading core.44066... 13ms
> getting status...
assert.js:102
  throw new assert.AssertionError({
        ^
AssertionError: "mdb: failed to initialize //lib/libc_db.so.1: libthread_db call failed unexpectedly\nmdb: warning: debugger will only be able t == ""
    at /opt/local/lib/node_modules/corevis/corevis.js:103:12
    at done (/opt/local/lib/node_modules/corevis/lib/mdb.js:92:5)
    at Socket.onstdout (/opt/local/lib/node_modules/corevis/lib/mdb.js:70:7)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Pipe.onread (net.js:397:31)
```

**Comment by bahamas10** [comment]
fixed in v0.0.2
